
<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'About' => 'A propos de',
    'Are you sure you want to delete this item?' => 'Confirmez-vous la suppression de cet élément?',
    'body'=> 'Texte',
    'Change on password' => 'Changement de mot de passe',
    '- Choose Your Permissions -'=>'- Choisis tes permissions -',
    'Congratulations!' => 'Félicitations',
    'Contact' => 'Contact',
    'Create'=> 'Créer',
    'Created At' => 'Crée le',
    'created_by'=> 'Crée par',
    'Create Status'=> 'Créer un statut',
    'Delete' => 'Supprimer',
    'email'=> 'email',
    'E-mail confirmation' => 'E-mail de confirmation',
    'Editing' => 'Modifier',
    'Heading' => 'Entête',
    'Home' => 'Accueil',
    'ID' => 'ID',
    'If you have business inquiries or other questions, please fill out the following form to contact us. Thank you.'=>'Si vous avez des questions d affaires ou autres, veuillez remplir le formulaire suivant pour nous contacter',
    'Login' => 'Login',
    'Logout' => 'Logout',
    'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.' => '',
    'Message' => 'Message',
    'message' => 'message',
    'message:ntext' => 'message:ntext',
    'My Company' => 'My company',
    //'My Yii Application' => '',
    'name'=> 'nom',
    'Password recovery' => 'Retrouver mot de passe',
    'Permissions' => 'Permissions',
    'permissions' => 'permissions',
    'Private'=> 'Privé',
    'Public' => 'Public',
    'Registration' => 'Enregistrement',
    'Reset'=>'Reset',
    'Status' => 'Status',
    'Statuses' => 'statuts',
    'subject'=> 'Objet',
    'Submit'=> 'Soumettre',
    'Text' => 'Texte',
    'Thank you for contacting us. We will respond to you as soon as possible.'=>'Merci de nous avoir contacté. Nous vous répondrons dès que possible .',
    'updated_at' => 'mis à jour le',   
    'Update Status:' => 'Mettre à jour le statut',
    'Update' => 'Mise à jour',
    'Updated At' => 'Mis à jour le',
    'verifyCode'=> 'Code de vérification',
    'view' => 'vue',
    'You have successfully created your Yii-powered application.' => 'Vous avez crée votre application Yii-powered avec succès',
    'You have no permission to delete this content'=> 'Votre rôle ne vous permet pas cette action',
    'Your Status Update' => 'Mis à jour de votre statut',   
   
   
   
    
   
    ];
