<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '- Choose Your Permissions -' => '',
    'About' => '',
    'Are you sure you want to delete this item?' => '',
    'Change on password' => '',
    'Congratulations!' => '',
    'Contact' => '',
    'Create' => '',
    'Create Status' => '',
    'Created At' => '',
    'Delete' => '',
    'E-mail confirmation' => '',
    'Editing' => '',
    'Heading' => '',
    'Home' => '',
    'ID' => '',
    'Login' => '',
    'Logout' => '',
    'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et
                    dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip
                    ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu
                    fugiat nulla pariatur.' => '',
    'Message' => '',
    'My Company' => '',
    'My Yii Application' => '',
    'Password recovery' => '',
    'Permissions' => '',
    'Private' => '',
    'Public' => '',
    'Registration' => '',
    'Reset' => '',
    'Search' => '',
    'Status' => '',
    'Statuses' => '',
    'Text' => '',
    'Update' => '',
    'Update Status:' => '',
    'Updated At' => '',
    'You have successfully created your Yii-powered application.' => '',
    'Your Status Update' => '',
    'created_at' => '',
    'message' => '',
    'permissions' => '',
    'updated_at' => '',
    'view' => '',
    'message:ntext' => '@@@@',
];
